from . import sale_inscription
from . import sale_order
from . import sale_order_line
from . import event_launch_order
from . import event_registration
from . import musical_level
from . import musical_tessiture
from . import event_type
from . import res_family
from . import res_partner
from . import product_pricelist
from . import product_pricelist_item